[package]
name = "zegois_music"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/library.rs"

[dependencies]
wasm-bindgen = "0.2"
ample = { version = "0.2.0", path="crates/ample" }
webspace = { version = "0.2.0", path="crates/webspace" }
humans = { version = "0.2.0", path="crates/humans" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioContext",
    "AudioDestinationNode",
    "AudioNode",
    "AudioScheduledSourceNode",
    "CanvasGradient",
    "CanvasRenderingContext2d",
    "Document",
    "DomRect",
    "Element",
    "EventTarget",
    "HtmlButtonElement",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "MouseEvent",
    "Window",
] }
